Fix example code to work properly
statikbe/laravel-filament-flexible-content-blocks pull request #25
Opened 2023-11-17 17:53 UTC by sjardim

2023-11-21 11:07 UTC, sten requested changes
@sjardim Thanks a lot for the example upgrade. Can you have a look at my remarks? Thanks!

2023-11-21 11:07 UTC, sten commented on README.md
> +- `artesaos/seotools`: this is a soft dependency, you can use a different package to handle the SEO fields output if you like.
There is no real dependency on this library. It is only used in the examples. So I do not like to include it. You can use whatever you want. 

In the future, I am planning to implement support for additional fields for SEO metadata types, like articles, pages, how-to lists, etc. Maybe other libs are more useful for this and we will have to make a choice. For now, it is nowhere used in the actual library.

We can add in the section about the example that it depends on `artesaos/seotools`

2023-11-21 11:07 UTC, sten commented on composer.json
> +        "artesaos/seotools": "^1.2",
Please, remove. See comment above.

2023-11-21 11:07 UTC, sten commented on example/app/View/Components/BaseLayout.php
> +class baseLayour extends Component
Typo in class name: BaseLayout

2023-11-21 13:33 UTC, sjardim commented on README.md
> +- `artesaos/seotools`: this is a soft dependency, you can use a different package to handle the SEO fields output if you like.
Hi Sten! My pleasure! I'll make the changes and will get back to ya. 

I am also working on another example, integrating [pboivin/filament-peek](https://github.com/pboivin/filament-peek). It's working right now but needs some tweaks. Maybe someone will find it useful :)

Take care!

2023-11-21 14:09 UTC, sten commented on README.md
> +- `artesaos/seotools`: this is a soft dependency, you can use a different package to handle the SEO fields output if you like.
@sjardim That would be really cool to integrate it with Filament Peek. We can maybe have a look on how we can closely integrate it in the package if it is not too complicated.

2024-01-22 21:39 UTC, sten commented
@sjardim Thanks for the help! I went through the example and added your suggestions!

2024-01-22 21:39 UTC, closed without merging