Kul blocks
statikbe/laravel-filament-flexible-content-blocks pull request #53
Opened 2024-11-14 14:11 UTC by sevbesau

### Description

Added kul bootstrap components

### Reason for this change

We want to be able to reuse these components quickly

2024-12-03 14:01 UTC, sten requested changes

2024-12-03 14:01 UTC, sten commented on config/filament-flexible-content-blocks.php
> +
Ik zou dat niet in een var steken in de config maar eventueel een enum voor maken of gewoon in de theme config array in comments zetten.

2024-12-03 14:01 UTC, sten commented on resources/views/components/bootstrap4-kul/call-to-action.blade.php
> +
Add @if($callToAction->url) around <a>

2024-12-11 16:13 UTC, sten commented
@sevbesau Ready to merge?

2025-03-18 21:48 UTC, sten requested changes
@sevbesau Can you have a look at my questions?
Looks good, ready to merge after these fixes. Thanks!

2025-03-18 21:48 UTC, sten commented on config/filament-flexible-content-blocks.php
> +                'class' => 'w-full md:w-3/4',
@sevbesau This is for the tailwind styling, right?

2025-03-18 21:48 UTC, sten commented on resources/views/content-blocks/bootstrap4-kul/image.blade.php
> +<section id="image" class="card {{ $getBackgroundColourClass() }} tw-w-full">
@sevbesau do you want all sections to have the same ID?

2025-05-08 11:38 UTC, sevbesau commented on config/filament-flexible-content-blocks.php
> +                'class' => 'w-full md:w-3/4',
yes

2025-05-08 11:38 UTC, sevbesau commented on resources/views/content-blocks/bootstrap4-kul/image.blade.php
> +<section id="image" class="card {{ $getBackgroundColourClass() }} tw-w-full">
no

2025-05-08 11:42 UTC, merged